spring.application.name=esign

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/esign-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:developer}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rahasia}
spring.datasource.driver-class-name=org.postgresql.Driver

# API config
spring.jpa.hibernate.ddl-auto=update
server.port=${DB_SERVER_PORT:3000}
server.error.include-stacktrace=never

# JWT config
esign-api.jwt.secret=${JWT_SECRET:ierkejrkdkfieruejrkeieruieurieurdkfd}
esign-api.jwt.expiration=${JWT_EXPIRATION:900000}
esign-api.jwt.issuer=${JWT_ISSUER:Esign API}
esign-api.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# super admin config
esign_api.super-admin.name=${SUPER_ADMIN_NAME:Admin Super}
esign_api.super-admin.username=${SUPER_ADMIN_USERNAME:supmin123}
esign_api.super-admin.email=${SUPER_ADMIN_EMAIL:supmin@esign.com}
esign_api.super-admin.password=${SUPER_ADMIN_PASSWORD:123456}

# Swagger Path
springdoc.api-docs.path=/api-docs

# gmail smtp
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Image path
esign-api.image.path=${IMAGE_PATH:storage/uploads/image}

# Document path
esign-api.document.path=${DOC_PATH:storage/uploads/documents}

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000

# Frontend Url
esign_api.frontend.url=${FRONTEND_URL:http://localhost:4000}